using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace mitaywalle.Input
{
	public class InputActionsCodePostprocessor : AssetPostprocessor
	{
		private const string GeneratedMarker = "This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator";
		private const string EmbeddedAssetField = "        private readonly bool _isEmbeddedAsset;";
		private const string AssetPropertyPattern = "(        public InputActionAsset asset \\{ get;(?: set;)? \\}\\n)";
		private const string DisposeOriginal = "        public void Dispose()\n        {\n            UnityEngine.Object.Destroy(asset);\n        }";
		private const string DisposeWithEmbeddedGuard =
			"        public void Dispose()\n        {\n            if (_isEmbeddedAsset)\n            {\n                UnityEngine.Object.Destroy(asset);\n            }\n        }";
		private const string DisposeWithDisable =
			"        public void Dispose()\n        {\n            Disable();\n\n            if (_isEmbeddedAsset)\n            {\n                UnityEngine.Object.Destroy(asset);\n            }\n        }";

		private static readonly Regex ClassRegex = new("public partial class @(?<className>[A-Za-z_][A-Za-z0-9_]*)\\s*:", RegexOptions.Compiled);
		private static readonly Regex AssetPropertyRegex = new(AssetPropertyPattern, RegexOptions.Compiled);

		private static void OnPostprocessAllAssets(string[] importedAssets,
		                                           string[] deletedAssets,
		                                           string[] movedAssets,
		                                           string[] movedFromAssetPaths)
		{
			foreach (string assetPath in importedAssets)
			{
				if (!assetPath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
					continue;

				PatchGeneratedInputActions(assetPath);
			}
		}

		private static void PatchGeneratedInputActions(string assetPath)
		{
			string fullPath = Path.GetFullPath(assetPath);
			if (!File.Exists(fullPath))
				return;

			byte[] bytes = File.ReadAllBytes(fullPath);
			bool hasBom = bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF;
			string source = Encoding.UTF8.GetString(hasBom ? bytes[3..] : bytes);
			if (!source.Contains(GeneratedMarker) || !source.Contains("IInputActionCollection2"))
				return;

			string newline = source.Contains("\r\n") ? "\r\n" : "\n";
			bool hasFinalNewline = source.EndsWith("\n", StringComparison.Ordinal);
			string normalizedSource = NormalizeLineEndings(source);
			string patchedSource = PatchSource(normalizedSource);
			if (patchedSource == normalizedSource)
				return;

			string output = newline == "\r\n" ? patchedSource.Replace("\n", "\r\n") : patchedSource;
			if (hasFinalNewline && !output.EndsWith(newline, StringComparison.Ordinal))
				output += newline;

			if (!hasFinalNewline && output.EndsWith(newline, StringComparison.Ordinal))
				output = output[..^newline.Length];

			File.WriteAllText(fullPath, output, new UTF8Encoding(hasBom));
			AssetDatabase.ImportAsset(assetPath, ImportAssetOptions.ForceUpdate);
		}

		private static string PatchSource(string source)
		{
			Match classMatch = ClassRegex.Match(source);
			if (!classMatch.Success)
				return source;

			string className = classMatch.Groups["className"].Value;
			string externalConstructorSignature = $"        public @{className}(InputActionAsset asset)";
			string result = source;

			if (!result.Contains(EmbeddedAssetField))
				result = AddEmbeddedAssetField(result);

			if (!result.Contains(externalConstructorSignature))
				result = AddExternalAssetConstructor(result, className);

			if (result.Contains(DisposeOriginal))
				result = result.Replace(DisposeOriginal, DisposeWithDisable);

			if (result.Contains(DisposeWithEmbeddedGuard))
				result = result.Replace(DisposeWithEmbeddedGuard, DisposeWithDisable);

			return result;
		}

		private static string AddEmbeddedAssetField(string source)
		{
			return AssetPropertyRegex.Replace(source, $"$1\n{EmbeddedAssetField}\n", 1);
		}

		private static string AddExternalAssetConstructor(string source, string className)
		{
			string constructorSignature = $"        public @{className}()";
			int constructorStart = source.IndexOf(constructorSignature, StringComparison.Ordinal);
			if (constructorStart < 0)
				return source;

			string jsonEndMarker = "\n}" + "\");";
			int jsonEnd = source.IndexOf(jsonEndMarker, constructorStart, StringComparison.Ordinal);
			if (jsonEnd < 0)
				return source;

			jsonEnd += jsonEndMarker.Length;

			string destructorSignature = $"\n\n        ~@{className}()";
			int destructorStart = source.IndexOf(destructorSignature, jsonEnd, StringComparison.Ordinal);
			if (destructorStart < 0)
				return source;

			string constructorCloseMarker = "\n        }";
			int constructorClose = source.LastIndexOf(constructorCloseMarker, destructorStart, StringComparison.Ordinal);
			if (constructorClose < jsonEnd)
				return source;

			string defaultConstructorJson = source[constructorStart..jsonEnd];
			string actionMapInitialization = source[jsonEnd..constructorClose];
			string replacement =
				defaultConstructorJson +
				"\n            _isEmbeddedAsset = true;" +
				actionMapInitialization +
				"\n        }" +
				$"\n\n        public @{className}(InputActionAsset asset)" +
				"\n        {" +
				"\n            if (asset == null)" +
				"\n                throw new ArgumentNullException(nameof(asset));" +
				"\n" +
				"\n            this.asset = asset;" +
				actionMapInitialization +
				"\n        }";

			return source[..constructorStart] + replacement + source[(constructorClose + constructorCloseMarker.Length)..];
		}

		private static string NormalizeLineEndings(string source)
		{
			return source.Replace("\r\n", "\n").Replace("\r", "\n");
		}
	}
}
